import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Container from "@/components/Container/Container";
import ProfileCardList from "@/components/Card/ProfileCardList/ProfileCardList";
import ProfileCard from "@/components/Card/ProfileCard/ProfileCard";
import { server } from "@/config";
import { useRouter } from "next/router";
import { Profile } from "@/interfaces/profile.model";
import Section from "@/components/Layout/Section/Section";
import { useAuth } from "@/contexts/AuthContext";
import { useEffect } from "react";
import withAuth from "@/components/Route/withAuth";

interface HomeProps {
  recommend: Profile[];
}

const Home = ({ recommend }: HomeProps) => {
  const router = useRouter();
  const { user } = useAuth();
  useEffect(() => {
    // Check if user is not authenticated and redirect to login page
    if (!user) {
      router.push("/login");
    }
  }, [user, router]);

  if (!user) {
    // User is not authenticated, return null to prevent rendering of the home page
    return null;
  }

  return (
    <>
      <Head>
        <title>coreer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Section title={"Top Picks"}>
            <ProfileCardList large={true}>
              {recommend.map((item) => (
                <ProfileCard profile={item} />
              ))}
            </ProfileCardList>
          </Section>
        </Container>
      </main>
    </>
  );
};

export const getServerSideProps = async (context: any) => {
  const recommendationsRes = await fetch(`${server}/recommend/34991625/5`);

  let recommend = await recommendationsRes.json();

  return {
    props: {
      recommend: recommend.recommendations,
    },
  };
};

export default withAuth(Home);
